Added getting started section to README
Valbrand/tibei pull request #11
Opened 2017-10-12 15:41 UTC by Valbrand

2017-10-12 15:51 UTC, Valbrand commented
@dichaves revisa o texto do tutorial, por favor?

2017-10-26 13:57 UTC, dichaves requested changes
Tá ótimo <3

2017-10-26 13:57 UTC, dichaves commented on README.md
> +The `ConnectionResponder` protocol has several other lifecycle methods that can be seen in the sample application and in the [docs](http://www.dvalbrand.com/tibei).
Dar mais ênfase à documentação

2017-10-26 13:57 UTC, dichaves commented on README.md
> +Creating a server is as simple as creating an instance of the `ServerMessenger` class and calling its `publishService` method:
"is as simple as" faz parecer que você só tá dando um exemplo

2017-10-26 13:57 UTC, dichaves commented on README.md
> +This will make the client start looking for services with the given identifier. Whenever the list of available services with the identifier `"myAppName"` changes, the `ClientMessenger` instance will
"An example that connects" tá confuso, é o exemplo que conecta ou é outra coisa? Poderia ser "an example where it connects" ou algo tipo

2017-10-26 13:57 UTC, dichaves commented on README.md
> +The `serviceIdentifier` argument serves as a means to make your app's service distinguishable from other applications and devices that may also be using Bonjour nearby.
Falar de Bonjour antes

2017-11-07 14:36 UTC, hpbl commented
bora ver hein? need docs

2018-10-26 12:42 UTC, merged